// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybiobcatqnnzjmrhmnfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliaW9iY2F0cW5uemptcmhtbmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjkzMzMsImV4cCI6MjA3MDMwNTMzM30.ynfuD5A8fAKVoSmO8l8MDj6qmtHSgighTpOiUpchu6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});